name: publish_jumpseat_on_release

on:
  release:
    types: [published]

jobs:
  publish_to_dockerhub:
    name: publish_jumpseat_on_release_publish_to_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: publish_jumpseat_on_release_publish_to_dockerhub_checkout
        uses: actions/checkout@v4

      - name: publish_jumpseat_on_release_publish_to_dockerhub_login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish_jumpseat_on_release_publish_to_dockerhub_setenv
        run: echo "FLATTENED_TAG=${{ vars.DOCKER_REPO_JUMPSEAT }}:release-$(git log -1 --format=%cd --date=format:%Y%m%dh%H%M%S)" >> $GITHUB_ENV

      - name: publish_jumpseat_on_release_publish_to_dockerhub_buildandpublish
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.FLATTENED_TAG }}
